Duke-GCB/gcb-ansible-roles

docker_webapp/tasks/main.yml, imads_webapp/tasks/main.yml, imads_webapp/tasks/setup_portal.yml, imads_webapp/tasks/setup_postgres.yml, imads_webapp/tasks/setup_vacuum.yml
- Removes become from imads playbook
- Assumes now that docker and docker-py are installed
- Assumes access to the {{ imads.data_root }} directory for placing all incoming files
- Assumes that remote user has access to docker socket (likely via
docker group)
- Avoids rewriting postgresql.conf (since this gets owned by root) in
favor of specifying config options with -c
- Sets SELinux type of ssl cert/key
These changes were developed in gcb-ansible repo, but were not merged before splitting roles into separate repo
=> Reworks imads playbook to not require sudo

bespin_job_watcher/tasks/main.yml, bespin_lando/tasks/main.yml, bespin_web/tasks/main.yml
We are moving the images from quay to docker due to ease of automating container rebuilds from multiple github repositories.
=> Remove quay from bespin images

bespin_web/tasks/main.yml
Made some improvements while expanding to a second bespin environment
- bespin-ui is now downloaded at ansible provisioning time, allowing us to choose between the dev and prod builds and specific versions.
- Removes unused BESPIN_CORS_HOST
=> Updates for bespin-web deployment

bespin_job_watcher/templates/config.j2
Previously host was hardcoded to `bespin-rabbit`
=> Update bespin_job_watcher role to use rabbit host from variable

jupyterhub/defaults/main.yml, jupyterhub/tasks/main.yml
RT Ticket requests increasing the runtime allotted to the jupyterhub job. This allows us to adjust the runtime in a variable (default provided).
=> Allow jupyterhub runtime/mem to be specified as variables

bespin_lando/tasks/main.yml, bespin_lando/templates/lando_config.yml.j2
- Renames `bespin_settings.worker_openstack` -> `bespin_settings.lando` as these are settings for the lando config.
- Role to create lando docker container now expects tagged docker image version from `bespin_settings.lando.version`.
- Removes `vm_settings` from lando config template (details now provided in API)
=> Bespin job vmsettings

copy_bespin_hosts/README.md, copy_bespin_hosts/tasks/main.yml
Changes copy_bespin_hosts to read the IP addresses from the inventory.
Previously we depended upon having a local /etc/hosts file.
This will allow bespin deployment from a central location.
=> setup Bespin server's hosts file based on the inventory

bespin_web/tasks/loaddata.yml
Django manage commands may return nonzero if data already loaded. This was causing the playbook to stop
=> Ignores errors when loading data in bespin-web

update_apt_cache/tasks/main.yml
Role would fail on yum systems
=> Fix update_apt_cache to only run on debian

d4s2_webapp/README.md, d4s2_webapp/defaults/main.yml, d4s2_webapp/files/nginx.conf, d4s2_webapp/tasks/main.yml, docker_webapp/tasks/main.yml
Adds an Nginx container to the role. 
Nginx is configured to handle https and proxy traffic to the app container. This simplifies the app container (no longer complicated by apache) and provides an easier path to serving the [Ember-based datadelivery-ui](https://github.com/Duke-GCB/datadelivery-ui)
Related to https://github.com/Duke-GCB/D4S2/pull/164
=> Update d4s2 webapp role to use nginx reverse proxy

bespin_job_watcher/tasks/main.yml, bespin_lando/tasks/main.yml, bespin_mailer/tasks/main.yml, bespin_web/tasks/loaddata.yml, bespin_web/tasks/run-server.yml, build_docker_image/README.md, build_docker_image/defaults/main.yml, build_docker_image/tasks/main.yml, build_ember_app/README.md, build_ember_app/defaults/main.yml, build_ember_app/tasks/main.yml, list_docker_containers/tasks/main.yml
Updates and additions to bespin roles to allow for deployment from source without waiting for Docker Hub automated builds or CI Ember builds.
Tested on bespin-dev with updated playbook in matching gcb-ansible branch.
- Adds `build_docker_image` role to clone a git repo and build a docker image
- Adds `build_ember_app` role to clone a git repo and build an ember application using Docker into a docker volume
- Adds `list_docker_containers` role to report a list of running docker containers and their images:versions
- Updates bespin roles to build images on-demand from source+Dockerfile rather than pulling images from Docker Hub
=> Roles for building bespin docker images during deployment

bespin_lando_worker/README.md, bespin_lando_worker/defaults/main.yml, bespin_lando_worker/tasks/main.yml
Copied this role from the [gcb-ansible](https://github.com/Duke-GCB/gcb-ansible) repo.
Includes modifications to be more flexible.
Variable `lando_version` specifies the version of lando to install.
Variable `cwl_runner_version` specifies the version of cwltool to install( or whatever tool is specified via `cwl_runner)`.
=> add bespin_lando_worker from gcb-ansible

jupyterhub/tasks/main.yml, jupyterhub/vars/main.yml
This change will update the jupyterhub slurm script template to source a .spawnerrc file in the user's home directory instead of loading the default environment
If the custom environment does not provide a jupyterhub-singleuser command, an error message is displayed
=> Allow custom jupyterhub environment in spawner slurm script

bespin_lando_worker/tasks/main.yml
cwltool uses [nodejs locally if installed](https://github.com/common-workflow-language/cwltool/blob/592a7e6c5e10b96a3b15567bc1cdb3c8b89e2976/cwltool/sandboxjs.py#L62-L75). If not, it runs nodejs in Docker, which can lead to lots of additional docker containers.
This change installs nodejs into the lando worker image, so that worker VMs don't need to create those extra containers
=> Install nodejs in bespin_lando_worker

prune_docker/README.md, prune_docker/defaults/main.yml, prune_docker/tasks/main.yml
- Adds `prune_docker` role accepting variables `prune_images` and `prune_containers`
- By default, both are `yes` and this role will remove all stopped containers from a host and delete any unused images
- Uses docker prune commands and prints output with `debug` to show what's been removed/reclaimed
- This role is intended to be used after deploying applications with `build_docker_image`
=> Role to remove unused docker containers/images

bespin_lando_worker/defaults/main.yml, bespin_lando_worker/tasks/main.yml
During development, it's useful to build an image installing lando from a branch on github.
=> Adds `lando_install_source` variable to install lando from GitHub

bespin_lando/templates/lando_config.yml.j2, bespin_lando_worker/README.md, bespin_lando_worker/defaults/main.yml, bespin_lando_worker/tasks/main.yml
Adds command settings config to lando based on bespin_settings (this specifies the lando-util commands to run). Changes bespin_lando_worker to install a utility package with the default being lando-util.
=> use lando-util in bespin lando worker

bespin_lando_k8s/README.md, bespin_lando_k8s/tasks/create-services.yml, bespin_lando_k8s/tasks/main.yml, bespin_lando_k8s/templates/lando_k8s_config.yml.j2
Changes `bespin_lando_k8s` role  to allow bespin to use multiple k8s clusters.
This change adds a `k8s_clusters` field to the `bespin_settings` dictionary.
`k8s_clusters` is a dictionary where the key is a name to assign to the cluster.
See https://github.com/Duke-GCB/gcb-ansible-roles/blob/lando-k8s-multi-tenant/bespin_lando_k8s/README.md for more details.
=> lando k8s multi tenant

d4s2_webapp/handlers/main.yml, d4s2_webapp/tasks/main.yml
- Adds a handler `restart web` that restarts the datadelivery web proxy container
- Triggers handler when services proxied by the container are changed
Verified by 
1. Running playbook without changes to versions. Web container stays running
2. Downgrade version of datadelivery-ui, run playbook. Web container restarts at end of playbook and routes traffic correctly without 503 errors.
Fixes #71
=> Fixes 503 errors from proxy when deploying datadelivery

bespin_lando_k8s/README.md, bespin_lando_k8s/tasks/create-services.yml, bespin_lando_k8s/tasks/main.yml, bespin_lando_k8s/tasks/remove-services.yml
This will allow a user to uninstall the associated containers and config files when lando_k8s_state = 'absent'. Also moves bespin_settings.k8s_clusters out to a separate k8s_clusters variable to allow deploying without modifying bespin_settings.
=> Adds lando_k8s state to bespin_lando_k8s role

rnaseq/tasks/main.yml
Updates the R installation `repos` since http://cran.us.r-project.org no longer resolves.
Installs Cython due to errors about this not being installed by HTSeq.
=> rnaseq software requirement fixes

data-driven-hypothesis/README.md, data-driven-hypothesis/defaults/main.yml, data-driven-hypothesis/tasks/main.yml
Adds a role that can be used to deploy DDH based on the master branch of [matthewhirschey/ddh](https://github.com/matthewhirschey/ddh). This role is based on the [ddh openshift README](https://github.com/matthewhirschey/ddh/blob/master/openshift/README.md).
=> Role to deploy datadrivenhypothesis.org

imads_webapp/defaults/main.yml, imads_webapp/tasks/setup_portal.yml
Configures imads docker container to use log rotation. Otherwise when the log fills up and the pod is restarted apache fails to start due to being out of space.
=> add options to limit imads portal log size

build_docker_image/tasks/main.yml
Changes build_docker_image role to assure destination directory is absent before running git clone.
Also assures base directory exists.
Fixes #86
=> fix build_docker_image issue #86
