bespin_job_watcher/tasks/main.yml
bespin_job_watcher/templates/config.j2
bespin_web/tasks/main.yml

Changes to deploy bespin job watcher
Also includes changes to set environment variables for bespin-api's connection to rabbitmq.

Bespin job watcher

---

bespin_job_watcher/tasks/main.yml
bespin_job_watcher/templates/config.j2
bespin_web/tasks/main.yml

Assumes `files` directory will contain SSL certs.

SSL setup for bespin/bespin-ws

---

bespin_web/tasks/main.yml

Passes group manager setup to bespin-web.

Add bespin grouper environment variables

---

rnaseq/tasks/main.yml

Added X11 forwarding functionality, specified older version of firefox to work around problems caused by multi-process default in latest version, altered yum.conf to exclude firefox from yum update unless explicitly requested by users, and created /work directory for users since /home was smaller than requested.

Rnaseq fixes

---

rnaseq/tasks/main.yml

Adds missing requirements for `DESeq2`.
Adds R gplots package.
Switches to regular java instead of `headless`.

Rnaseq r java fixes

---

bespin_database/tasks/main.yml
bespin_lando/tasks/main.yml
bespin_web/tasks/loaddata.yml

Fixes clouded dependency issue
also removes unnecessary /etc/external volumes

Migrate database before loading initial data

---

jupyterhub/defaults/main.yml
jupyterhub/files/jupyterhub.service
jupyterhub/files/sudo_jupyter
jupyterhub/tasks/main.yml
jupyterhub/templates/jupyterhub-init.j2
jupyterhub/templates/jupyterhub.service.j2
jupyterhub/vars/main.yml

This role is used to install JupyterHub with some configurable options (Current usage in bold):
- OS: Debian or **RedHat**
- Spawner: Docker, Sudo, or **Batch (Slurm)**
- Authenticator: GitLab OAuth or **PAM**

Jupyterhub role

---

bespin_web/tasks/run-server.yml

Reflecting changes in https://github.com/Duke-GCB/bespin-api/pull/111

Update bespin-web to use duke-gcb/bespin-api:<version>-apache

---

hook_build/tasks/main.yml
hook_build/templates/build-module.sh.j2
hook_build/templates/hook-build-init.j2
hook_build/templates/hook-build-service.j2

role hook_build to run [hook-build](github.com/Duke-GCB/hook-build)

Hook build

---

bespin_web/tasks/loaddata.yml

Fix docker image in bespin_web/tasks/loaddata

---

bespin_web/tasks/run-server.yml

This is to fix an issue where the docker environment was not visible to the starting scripts.
Fixes https://github.com/Duke-GCB/gcb-ansible/issues/48
Ansible docker_container module docs: http://docs.ansible.com/ansible/latest/docker_container_module.html

Add restart true to the bespin_web role

---

copy_bespin_hosts/tasks/main.yml

consistently use dashes for hostnames/aliases

expect bespin hostname aliases to contain dashes

---

d4s2_webapp/tasks/main.yml

Requires https://github.com/Duke-GCB/D4S2/pull/147

Change d4s2 role to run process_tasks

---

d4s2_webapp/defaults/main.yml
d4s2_webapp/files/nginx.conf
d4s2_webapp/tasks/main.yml

Adds tasks to install datadelivery-ui container in d4s2_webapp role
- Expects image name to be provided in the same way as d4s2
- Adds the ability to select which service to deploy based on tag `api` or `ui`

Tasks for datadelivery-ui container in d4s2_webapp role

---

imads_webapp/tasks/setup_portal.yml
imads_webapp/tasks/setup_postgres.yml
imads_webapp/tasks/setup_vacuum.yml
imads_webapp/tasks/setup_worker.yml

Adds variable `db_image` to specify postgres image rather than hard coded version.
These changes are so the playbook can use `build_docker_image`.

Update imads roles to read image name and version from variables

---

jupyterhub/tasks/main.yml

Raise jupyterhub spawner timeouts

---

jupyterhub/defaults/main.yml

Jupyterhub -extended req_runtime from 120 to 240

---

imads_webapp/tasks/setup_portal.yml

specify apache image for imads portal

---

jupyterhub/defaults/main.yml

Reverts Duke-GCB/gcb-ansible-roles#52
Decided to do edit in another repo.

Revert "Jupyterhub -extended req_runtime from 120 to 240"

---

bespin_lando_k8s/README.md
bespin_lando_k8s/tasks/main.yml
bespin_lando_k8s/templates/lando_k8s_config.yml.j2

Adds role to deploy lando k8s services.

Changes to deploy bespin lando k8s services

---

postgres_backup/README.md
postgres_backup/defaults/main.yml
postgres_backup/tasks/main.yml
postgres_backup/templates/backup-postgres.sh.j2

Adds `postgres_backup` role that will create daily backups of a database.
The backups will be stored in a mounted nfs  directory.

Adds role to backup a postgres database

---

webhook-proxy/README.md
webhook-proxy/tasks/main.yml
webhook-proxy/templates/index.html.j2
webhook-proxy/templates/site.conf.j2

This role sets up nginx and let's encrypt as a webhook
proxy for OpenShift.

Add webhook-proxy role
